/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEspnTeamsRouteImport } from './routes/api/public/espn-teams'
import { Route as ApiPublicEspnScoreboardRouteImport } from './routes/api/public/espn-scoreboard'
import { Route as ApiPublicEspnRosterRouteImport } from './routes/api/public/espn-roster'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEspnTeamsRoute = ApiPublicEspnTeamsRouteImport.update({
  id: '/api/public/espn-teams',
  path: '/api/public/espn-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEspnScoreboardRoute = ApiPublicEspnScoreboardRouteImport.update({
  id: '/api/public/espn-scoreboard',
  path: '/api/public/espn-scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEspnRosterRoute = ApiPublicEspnRosterRouteImport.update({
  id: '/api/public/espn-roster',
  path: '/api/public/espn-roster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/espn-roster': typeof ApiPublicEspnRosterRoute
  '/api/public/espn-scoreboard': typeof ApiPublicEspnScoreboardRoute
  '/api/public/espn-teams': typeof ApiPublicEspnTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/espn-roster': typeof ApiPublicEspnRosterRoute
  '/api/public/espn-scoreboard': typeof ApiPublicEspnScoreboardRoute
  '/api/public/espn-teams': typeof ApiPublicEspnTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/espn-roster': typeof ApiPublicEspnRosterRoute
  '/api/public/espn-scoreboard': typeof ApiPublicEspnScoreboardRoute
  '/api/public/espn-teams': typeof ApiPublicEspnTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/espn-roster'
    | '/api/public/espn-scoreboard'
    | '/api/public/espn-teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/espn-roster'
    | '/api/public/espn-scoreboard'
    | '/api/public/espn-teams'
  id:
    | '__root__'
    | '/'
    | '/api/public/espn-roster'
    | '/api/public/espn-scoreboard'
    | '/api/public/espn-teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicEspnRosterRoute: typeof ApiPublicEspnRosterRoute
  ApiPublicEspnScoreboardRoute: typeof ApiPublicEspnScoreboardRoute
  ApiPublicEspnTeamsRoute: typeof ApiPublicEspnTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/espn-teams': {
      id: '/api/public/espn-teams'
      path: '/api/public/espn-teams'
      fullPath: '/api/public/espn-teams'
      preLoaderRoute: typeof ApiPublicEspnTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/espn-scoreboard': {
      id: '/api/public/espn-scoreboard'
      path: '/api/public/espn-scoreboard'
      fullPath: '/api/public/espn-scoreboard'
      preLoaderRoute: typeof ApiPublicEspnScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/espn-roster': {
      id: '/api/public/espn-roster'
      path: '/api/public/espn-roster'
      fullPath: '/api/public/espn-roster'
      preLoaderRoute: typeof ApiPublicEspnRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicEspnRosterRoute: ApiPublicEspnRosterRoute,
  ApiPublicEspnScoreboardRoute: ApiPublicEspnScoreboardRoute,
  ApiPublicEspnTeamsRoute: ApiPublicEspnTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
